zeebe:
  client:
    cloud:
      clusterId: "cc7ab14a-e560-4bfb-a4fd-f2592a424177"
      clientId: "1YXMvOMwWffaiyehwlW_G8TknraS7ua9"
      clientSecret: "p3IRE30-ziSZxGQBPJn5Zq5QRchakVHtspo3JrARuuv-jX1JFLKb6hgZL6VpX0e6"
      region: "lhr-1"


spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: gu
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


