zeebe:
  client:
    cloud:
      clusterId: "cc7ab14a-e560-4bfb-a4fd-f2592a424177"
      clientId: "1YXMvOMwWffaiyehwlW_G8TknraS7ua9"
      clientSecret: "p3IRE30-ziSZxGQBPJn5Zq5QRchakVHtspo3JrARuuv-jX1JFLKb6hgZL6VpX0e6"
      region: "lhr-1"
    broker:
      contactPoint: 127.0.0.1:26500



spring:
  datasource:
    url: jdbc:postgresql://195.150.230.208:5432/2023_urban_grzegorz
    username: 2023_urban_grzegorz
    password: 35240
    hikari:
      max-lifetime: 2000000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: TIJO
    open-in-view: false
  mail:
    host: "live.smtp.mailtrap.io"
    port: 587
    username: "api"
    password: "5fbc80f01f9da4d5281b0a7776713a24"
    properties:
      mail:
        smtp:
          from: "Webstaurator@xn--kork-py-jpb.pl"
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2

logging:
  level:
    pl.urban.bpmn: DEBUG
    pl.urban.bpmn.workers: DEBUG
    pl.urban.bpmn.api.service: DEBUG

